# Generated by Django 5.2.3 on 2025-06-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
